#!/usr/bin/env python3

import argparse
from idiahdf5.fits2hdf5 import convert, DEFAULTS

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Tool for converting FITS images to the HDF5 format using the IDIA schema. Only the primary HDU is converted. The dimensions of the original image are preserved. Additional cached datasets may be stored in the file, as described in the options below.")
    
    parser.add_argument('filename', help='Input filename')
    
    parser.add_argument('--chunks', nargs="+", type=int, help='Chunks to use, order: Z Y X')
    parser.add_argument('--statistics', nargs="+", help='Axes along which statistics should be calculated, e.g. XY, Z, XYZ', default=DEFAULTS.statistics)
    parser.add_argument('--histograms', nargs="+", help='Axes along which histograms should be calculated, e.g. XY, Z, XYZ', default=DEFAULTS.histograms)
    parser.add_argument('--percentiles', nargs="+", help='Axes along which percentiles should be calculated, e.g. XY, Z, XYZ', default=DEFAULTS.percentiles)
    parser.add_argument('--swizzles', nargs="+", help='Axes for which swizzled datasets should be written, e.g. ZYXW', default=DEFAULTS.swizzles)
    parser.add_argument('--output-dir', help="Output directory. By default, the directory of the original file will be used. This parameter will be ignored if an absolute path is provided for the --output parameter.")
    parser.add_argument('--output', help="Output filename. By default, the original filename will be used, with the .fits suffix (if any) replaced by .hdf5. This filename may be a path. If it is an absolute path, the --output-dir parameter will be ignored.")
    parser.add_argument('--quiet', action='store_true', help="Suppress all print output.")
    parser.add_argument('--faster', action='store_true', help="Try to swizzle XYZ to ZYX more quickly, but using more memory.")
    
    # TODO if we want to split out stokes, we should pass in a stokes parameter
    
    args = parser.parse_args()
    
    convert(args)
